/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "auccbswepellxtoulbld"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1Y2Nic3dlcGVsbHh0b3VsYmxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4ODA4MzQsImV4cCI6MjA4MTQ1NjgzNH0.2x-H-Ih6-sVtFdVvhrKyYrLC0JIZ_Gszku6S16f05xo"